install.packages("IRkernel")
IRkernel::installspec(user = FALSE)
install.packages("readODS")
install.packages("ggplot2")
install.packages("gridExtra")
install.packages("officer")
install.packages("flextable")
